(in-package :%mfiano.graphics.image.color)

(defun find-transform-path (destination paths)
  (labels ((%find-transform-path (node result)
             (cond ((null node) nil)
                   ((and (consp node) (atom (car node))
                         (let ((current (car node)))
                           (if (eq destination current)
                               (cons current result)
                               (%find-transform-path (cdr node)
                                                     (cons current result))))))
                   ((and (consp node) (consp (car node)))
                    (or (%find-transform-path (car node) result)
                        (%find-transform-path (cdr node) result)))
                   (t (if (eq destination node)
                          (cons node result)
                          nil)))))
    (nreverse (%find-transform-path paths nil))))
