(in-package #:mfiano.graphics.tools.image)

(defun get-rgb-transform (from to illuminant-name)
  (declare (optimize speed))
  (let* ((transforms (rgb-transforms *context*))
         (from-space (color-space-name from))
         (to-space (color-space-name to))
         (key (list from-space to-space illuminant-name)))
    (declare (dynamic-extent key))
    (labels ((calculate-rgb-transform (rgb-space)
               (destructuring-bind ((rx ry) (gx gy) (bx by)) (coords rgb-space)
                 (declare (u:f32 rx ry gx gy bx by))
                 (let* ((r (v3:vec (/ rx ry) 1 (/ (- 1 rx ry) ry)))
                        (g (v3:vec (/ gx gy) 1 (/ (- 1 gx gy) gy)))
                        (b (v3:vec (/ bx by) 1 (/ (- 1 bx by) by)))
                        (scale (m3:*v3 (m3:invert (m3:mat r g b))
                                       (get-white-point illuminant-name))))
                   (m3:mat (v3:scale r (v3:x scale))
                           (v3:scale g (v3:y scale))
                           (v3:scale b (v3:z scale))))))
             (calculate-transform ()
               (etypecase from
                 (rgb (calculate-rgb-transform from))
                 (xyz (m3:invert (calculate-rgb-transform to))))))
      (u:if-found (transform (u:href transforms key))
        transform
        (setf (u:href transforms (copy-list key)) (calculate-transform))))))

(declaim (inline transform-rgb-xyz))
(defun transform-rgb-xyz (from to illuminant-name)
  (declare (optimize speed))
  (let ((transform (get-rgb-transform from to illuminant-name)))
    (m3:*v3! (data to) transform (data from))
    (setf (%illuminant-name to) illuminant-name)
    to))
